### ISSUE TITLE
Error: The node API for `babel` has been moved to `babel-core`.

### ISSUE THREAD

**Issue by condensa42** [ConsenSys/ether-pudding#12]
git clone https://github.com/ConsenSys/truffle
git clone https://github.com/ConsenSys/ether-pudding
cd ether-pudding
npm install
npm link
cd ../truffle
npm install
npm link ether-pudding 
TRUFFLE_NPM_LOCATION=`pwd` TRUFFLE_WORKING_DIRECTORY="/usr/local/lib/node_modules/ether-pudding" ./truffle.bash test 

TRUFFLE_NPM_LOCATION=`pwd` TRUFFLE_WORKING_DIRECTORY="/usr/local/lib/node_modules/ether-pudding" ./truffle.bash test 

/home/vagrant/truffle/node_modules/solc/bin/soljson-latest.js:1
aughtException",(function(ex){if(!(ex instanceof ExitStatus)){throw ex}}));Mod
                                                                    ^
Error: The node API for `babel` has been moved to `babel-core`.
  at Object.<anonymous> (/home/vagrant/ether-pudding/node_modules/babel/index.js:1:69)
  at Module._compile (module.js:456:26)
  at Module._extensions..js (module.js:474:10)
  at Object.require.extensions.(anonymous function) [as .js] (/home/vagrant/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:214:7)
  at Module.load (/home/vagrant/truffle/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/vagrant/ether-pudding/generator.js:6:13)
  at Module._compile (module.js:456:26)
  at normalLoader (/home/vagrant/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
  at Object.require.extensions.(anonymous function) [as .js] (/home/vagrant/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
  at Module.load (/home/vagrant/truffle/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/vagrant/truffle/lib/contracts.es6:11:24)
  at Module._compile (module.js:456:26)
  at normalLoader (/home/vagrant/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
  at Object.require.extensions.(anonymous function) [as .es6] (/home/vagrant/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
  at Module.load (/home/vagrant/truffle/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/vagrant/truffle/truffle.es6:15:17)
  at Module._compile (module.js:456:26)
  at normalLoader (/home/vagrant/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
  at Object.require.extensions.(anonymous function) [as .es6] (/home/vagrant/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at Object.<anonymous> (/home/vagrant/truffle/node_modules/babel/lib/_babel-node.js:144:25)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:902:3

**Comment by dreid93** [comment]
I also experience this issue though it was resolved when I ran `npm install https://github.com/VoR0220/ether-pudding.git#2409b30`. @VoR0220 has submitted PR's that resolve this issue.

**Comment by tcoulter** [comment]
Fixed.
