### ISSUE TITLE
undefined _iteratorError was thrown

### ISSUE THREAD

**Issue by barkthins** [ConsenSys/ether-pudding#14]
Attempting to call the .at function, I get a throw with an undefined symbol

code that did this:

```
 dstore = myContractPd.at(myContract.address);
```

```
/home/barkthins/npm-global/lib/node_modules/ether-pudding/build/ether-pudding.js:69
            throw _iteratorError;
                  ^
ReferenceError: Symbol is not defined
    at Contract.Pudding (/home/barkthins/npm-global/lib/node_modules/ether-pudding/build/ether-pudding.js:40:51)
    at new Contract (/home/barkthins/npm-global/lib/node_modules/ether-pudding/build/ether-pudding.js:210:82)
    at Function.at (/home/barkthins/npm-global/lib/node_modules/ether-pudding/build/ether-pudding.js:131:16)

```

**Comment by barkthins** [comment]
some more info:
console log of the Pudding contract myContractPd:
```
{ [Function: Contract]
  abi: 
   [ { constant: true,
       inputs: [],
       name: 'getData',
       outputs: [Object],
       type: 'function' },
     { constant: false,
       inputs: [],
       name: 'incrData',
       outputs: [Object],
       type: 'function' },
     { inputs: [], type: 'constructor' } ],
  binary: '0x6060604052620d903860005560488060176000396000f3606060405260e060020a60003504633bc5de3081146024578063a9b66f3114602d575b005b603e6000545b90565b603e6000805460010190819055602a565b6060908152602090f3',
  class_defaults: {} }
```

**Comment by tcoulter** [comment]
Alright, this is very old - apologies for the late response. Version 3.x has been released. Can you try 3.x and see if things work differently for you? Please open a new issue if you have trouble. Thanks!
