### ISSUE TITLE
Not working with node v6.0

### ISSUE THREAD

**Issue by zunware** [ConsenSys/ether-pudding#26]
I get the following error when using node v6.0 
I had to revert to v5.5 using nvm to fix the error.

Apparently it is missing a string parameter for the filename

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Module._compile (module.js:536:22)
    at /usr/local/lib/node_modules/truffle/node_modules/ether-pudding/loader.js:49:11
    at /usr/local/lib/node_modules/truffle/node_modules/ether-pudding/loader.js:30:7
    at done (/usr/local/lib/node_modules/truffle/node_modules/node-dir/lib/paths.js:27:13)
    at /usr/local/lib/node_modules/truffle/node_modules/node-dir/lib/paths.js:55:33
    at FSReqWrap.oncomplete (fs.js:117:15)
    at Function.module.exports.loopWhile (/usr/local/lib/node_modules/truffle/node_modules/deasync/index.js:72:22)
    at /usr/local/lib/node_modules/truffle/node_modules/deasync/index.js:44:19
    at Object.Config.gather (/usr/local/lib/node_modules/truffle/lib/config.js:304:5)
    at /usr/local/lib/node_modules/truffle/cli.js:251:31
    at /usr/local/lib/node_modules/truffle/node_modules/deasync/index.js:43:7
    at runTask (/usr/local/lib/node_mod
```

**Comment by thiagodelgado111** [comment]
Same issue here
