### ISSUE TITLE
Exception while deploying on testnet

### ISSUE THREAD

**Issue by chevdor** [ConsenSys/ether-pudding#37]
Running truffle beta 3.0.0

```
/usr/local/lib/node_modules/truffle/node_modules/ether-pudding/index.js:58
        network.abi.forEach(function(item) {
                   ^

TypeError: Cannot read property 'forEach' of undefined
    at /usr/local/lib/node_modules/truffle/node_modules/ether-pudding/index.js:58:20
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

**Comment by chevdor** [comment]
The issue probably came from truffle. After deleting the build folder and running the migration again, the issue no longer occurred.
