### ISSUE TITLE
Basic example throws 'TypeError: contract.abi.filter is not a function'

### ISSUE THREAD

**Issue by javgh** [ConsenSys/ether-pudding#9]
Hi there,

I have been using a previous version of ether-pudding (thanks for the work!) and am trying to upgrade to the latest release, but am having some difficulties.

```
npm install web3 ether-pudding
```

This gives me web3 in version 0.14.1 and ether-pudding in version 1.0.2 .

I'm trying to get a very simple example running, based on what's in the README. I think the README example is currently missing `Pudding.setWeb3(web3)`, right? I get `Cannot read property 'eth' of undefined` if I don't include that.

```
var Web3 = require('web3')
var web3 = new Web3()
var Pudding = require('ether-pudding')

web3.setProvider(new web3.providers.HttpProvider())
Pudding.setWeb3(web3)

var abi = '[{"constant":true,"inputs":[],"name":"hello","outputs":[{"name":"","type":"bool"}],"type":"function"}]'
var binary = '606060405260658060106000396000f360606040526000357c01000000000000000000000000000000000000000000000000000000009004806319ff1d21146037576035565b005b604260048050506058565b6040518082815260200191505060405180910390f35b6000600190506062565b9056'

var MyContract = Pudding.whisk(abi, binary)
var myContract = MyContract.at('0xabcd')
```

Running this, I now get this error:

```
TypeError: contract.abi.filter is not a function
    at addFunctionsToContract (/tmp/p/node_modules/web3/lib/web3/contract.js:56:18)
    at ContractFactory.at (/tmp/p/node_modules/web3/lib/web3/contract.js:251:5)
    at Function.at (/tmp/p/node_modules/ether-pudding/build/ether-pudding.js:124:39)
    at Object.<anonymous> (/tmp/p/letswhisk.js:12:29)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

Any ideas what I'm doing wrong or where things go wrong?

**Comment by tcoulter** [comment]
Hey there, thanks for the writeup. Your abi needs to be a Javascript Array
rather than a string. Go ahead and run that abi through JSON.parse first.

**Comment by javgh** [comment]
Aw, of course, thanks - that works!
